# Generated by Django 3.2.3 on 2021-05-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veille',
            fields=[
                ('Nom', models.CharField(max_length=55)),
                ('Prenom', models.CharField(max_length=55)),
                ('Date_de_naissance', models.DateField(blank=True)),
                ('Email', models.CharField(max_length=55)),
                ('Confirmation_email', models.EmailField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('Mot_de_passe', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.CharField(max_length=155)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_article', models.IntegerField()),
                ('titre_article', models.CharField(max_length=55)),
                ('lien_site', models.CharField(max_length=55)),
                ('lien_document', models.CharField(max_length=55)),
                ('date_article', models.DateField(auto_now=True)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
    ]
