# Generated by Django 3.2.3 on 2021-05-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0002_article_nouveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nouveau',
        ),
    ]
