# Generated by Django 3.2.3 on 2021-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0003_remove_article_nouveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nouveau',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
