# Generated by Django 3.2.3 on 2021-05-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0004_article_nouveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_auteur', models.CharField(max_length=55)),
                ('Domaine', models.CharField(max_length=55)),
                ('Mot_cle1', models.CharField(max_length=25)),
                ('Mot_cle2', models.CharField(max_length=25)),
                ('Mot_cle3', models.CharField(max_length=25)),
                ('date_req', models.DateField(auto_now=True)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
    ]
